[package]
name = "lfg-studio/freshynoid"
version = "1.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
NodeGraph = "lfg-studio/node-graph@1.0.0"
Signal = "dig1t/signal@1.0.1"
Trove = "sleitnick/trove@1.3.0" # https://sleitnick.github.io/RbxUtil/api/Trove